Repository IIS-ZPI/ZPI2020_zaoczni_Grupa_P, pull requests merged in 2021-01, with the labels that each got.

#55 Analiza Statystyczna
  pom.xml
  src/main/java/Main.java
  src/main/java/Validator.java
  src/main/java/functions/Session.java
  src/main/java/json/ApiConnect.java
  src/main/java/json/currency/CurrencyInfo.java
  src/main/java/json/currency/Rates.java
  src/main/java/json/table/CurrencyInfo.java
  src/main/java/json/table/Rates.java
  src/test/java/MainTest.java
Labels: enhancement

#56 Statystyki
  src/main/java/Main.java
  src/main/java/Validator.java
  src/main/java/functions/Statistics.java
Labels: enhancement

#64 Fix Methods : Session, Statistics
  src/main/java/functions/Session.java
  src/main/java/functions/Statistics.java
  src/test/java/MainTest.java
Labels: enhancement

#65 Testy jednostkowe (metody klas Validator, Session i Statistics)
  src/test/java/MainTest.java
  src/test/java/SessionTest.java
  src/test/java/StatisticsTest.java
  src/test/java/ValidatorTest.java
Labels: Testing

#66 Ready version 2.1
  README.md
  pom.xml
  src/main/java/Main.java
  src/main/java/Validator.java
  src/main/java/functions/Session.java
  src/main/java/functions/Statistics.java
  src/main/java/json/ApiConnect.java
  src/main/java/json/currency/CurrencyInfo.java
  src/main/java/json/currency/Rates.java
  src/main/java/json/table/CurrencyInfo.java
  src/main/java/json/table/Rates.java
  src/test/java/MainTest.java
  src/test/java/SessionTest.java
  src/test/java/StatisticsTest.java
  src/test/java/ValidatorTest.java
Labels: devops

#68 Testy oraz 3 funkcjonalność
  src/main/java/Main.java
  src/main/java/Validator.java
  src/main/java/functions/Session.java
  src/main/java/functions/Volatility.java
  src/test/java/SessionTest.java
  src/test/java/StatisticsTest.java
  src/test/java/VolatilityTest.java
Labels: Testing

#81 Poprawki do trzeciej funkcjonalności, dodano przedziały
  src/main/java/Main.java
  src/main/java/functions/Volatility.java
  src/test/java/VolatilityTest.java
Labels: enhancement

#96 Benchmark tests
  pom.xml
  src/main/java/functions/Session.java
  src/main/java/functions/Volatility.java
  src/test/java/BenchmarkTest/TestBenchmark.java
Labels: Testing, bug
